# Generated by Django 5.2.6 on 2025-09-15 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content',
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('trigger', models.CharField(blank=True, default='', max_length=50)),
                ('mode', models.CharField(choices=[('normal', 'normal'), ('restrict', 'restrict'), ('emergency', 'emergency')], default='normal', max_length=10)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_session',
                'indexes': [models.Index(fields=['user_ref', 'created_at'], name='recommendat_user_re_b512eb_idx'), models.Index(fields=['mode', 'created_at'], name='recommendat_mode_5e6b77_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.content')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.recommendationsession')),
            ],
            options={
                'db_table': 'item_rec',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('COMPLETE', 'COMPLETE'), ('EFFECT', 'EFFECT')], max_length=10)),
                ('value', models.FloatField(blank=True, null=True)),
                ('dwell_ms', models.IntegerField(blank=True, null=True)),
                ('watched_pct', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.content')),
                ('item_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itemrec')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.recommendationsession')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='ExposureCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_score', models.FloatField(blank=True, null=True)),
                ('chosen_flag', models.BooleanField(default=False)),
                ('x_item_vec', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.content')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='api.recommendationsession')),
            ],
            options={
                'db_table': 'exposure_candidate',
            },
        ),
        migrations.CreateModel(
            name='TriggerCategoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'trigger_category_policy',
                'indexes': [models.Index(fields=['trigger', 'is_active', 'priority'], name='trigger_cat_trigger_39caad_idx')],
                'unique_together': {('trigger', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserTodStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('as_of', models.DateField()),
                ('metric', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=20)),
                ('v_0_4', models.FloatField(blank=True, null=True)),
                ('v_4_8', models.FloatField(blank=True, null=True)),
                ('v_8_12', models.FloatField(blank=True, null=True)),
                ('v_12_16', models.FloatField(blank=True, null=True)),
                ('v_16_20', models.FloatField(blank=True, null=True)),
                ('v_20_24', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_tod_stats_daily',
                'indexes': [models.Index(fields=['user_ref', 'as_of'], name='user_tod_st_user_re_f7ef7c_idx'), models.Index(fields=['metric', 'stat'], name='user_tod_st_metric_4e4344_idx')],
                'unique_together': {('user_ref', 'as_of', 'metric', 'stat')},
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(max_length=50)),
                ('before', models.FloatField(blank=True, null=True)),
                ('after', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('effect', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.content')),
                ('item_rec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itemrec')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.recommendationsession')),
            ],
            options={
                'db_table': 'outcome',
                'indexes': [models.Index(fields=['outcome_type', 'created_at'], name='outcome_outcome_ddd376_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='itemrec',
            index=models.Index(fields=['session', 'rank'], name='item_rec_session_7a2912_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemrec',
            unique_together={('session', 'content')},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user_ref', 'created_at'], name='feedback_user_re_25c36a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['type', 'created_at'], name='feedback_type_2d5279_idx'),
        ),
        migrations.AddIndex(
            model_name='exposurecandidate',
            index=models.Index(fields=['session'], name='exposure_ca_session_ff1702_idx'),
        ),
        migrations.AddIndex(
            model_name='exposurecandidate',
            index=models.Index(fields=['content'], name='exposure_ca_content_a08591_idx'),
        ),
    ]
