# Generated by Django 5.2.6 on 2025-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='max_gw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='min_gw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='requires_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='tod_bucket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='triggercategorypolicy',
            index=models.Index(fields=['min_gw', 'max_gw'], name='trigger_cat_min_gw_a2858b_idx'),
        ),
        migrations.AddIndex(
            model_name='triggercategorypolicy',
            index=models.Index(fields=['tod_bucket'], name='trigger_cat_tod_buc_be99e2_idx'),
        ),
    ]
