# Generated by Django 5.2.6 on 2025-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update_trigger_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('address_road', models.CharField(blank=True, default='', max_length=300)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('epsg5174_x', models.FloatField(blank=True, null=True)),
                ('epsg5174_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_inside',
            },
        ),
        migrations.CreateModel(
            name='PlaceOutside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('address_road', models.CharField(blank=True, default='', max_length=300)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('sido', models.CharField(blank=True, default='', max_length=40)),
                ('sigungu', models.CharField(blank=True, default='', max_length=60)),
                ('eupmyeondong', models.CharField(blank=True, default='', max_length=80)),
            ],
            options={
                'db_table': 'place_outside',
            },
        ),
        migrations.CreateModel(
            name='UserStepsTodStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('d', models.DateField()),
                ('bucket', models.IntegerField()),
                ('cum_mu', models.FloatField()),
                ('cum_sigma', models.FloatField()),
                ('p20', models.FloatField()),
            ],
            options={
                'db_table': 'user_steps_tod_stats_daily',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='safety_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(default='CONTENT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['type'], name='content_type_846bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['lat', 'lng'], name='content_lat_15f86a_idx'),
        ),
        migrations.AddIndex(
            model_name='placeinside',
            index=models.Index(fields=['category'], name='place_insid_categor_2e7b24_idx'),
        ),
        migrations.AddIndex(
            model_name='placeoutside',
            index=models.Index(fields=['sido', 'sigungu'], name='place_outsi_sido_10334d_idx'),
        ),
        migrations.AddIndex(
            model_name='userstepstodstatsdaily',
            index=models.Index(fields=['user_ref', 'd'], name='user_steps__user_re_993ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='userstepstodstatsdaily',
            index=models.Index(fields=['bucket'], name='user_steps__bucket_2000c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstepstodstatsdaily',
            unique_together={('user_ref', 'd', 'bucket')},
        ),
    ]
