# Generated by Django 5.2.6 on 2025-09-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_steps_low_walk_outing_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('place_type', models.CharField(max_length=10)),
                ('place_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'place_exposure',
                'indexes': [models.Index(fields=['user_ref', 'place_type', 'place_id'], name='place_expos_user_re_e567cb_idx'), models.Index(fields=['created_at'], name='place_expos_created_4e03cb_idx')],
            },
        ),
    ]
