# Generated by Django 5.2.6 on 2025-09-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_placeexposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category'], name='content_categor_e4e50e_idx'),
        ),
    ]
