# Generated by Django 5.2.6 on 2025-09-20 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_content_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepts', models.IntegerField(default=0)),
                ('completes', models.IntegerField(default=0)),
                ('effects_sum', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_stat',
            },
        ),
        migrations.CreateModel(
            name='UserContentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('accepts', models.IntegerField(default=0)),
                ('completes', models.IntegerField(default=0)),
                ('effects_sum', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_content_stat',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrec',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='itemrec',
            name='user_ref',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='triggercategorypolicy',
            name='trigger_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemrec',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['is_active'], name='content_is_acti_ae331e_idx'),
        ),
        migrations.AddIndex(
            model_name='exposurecandidate',
            index=models.Index(fields=['created_at'], name='exposure_ca_created_0799eb_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrec',
            index=models.Index(fields=['session', 'created_at'], name='item_rec_session_cc68dd_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationsession',
            index=models.Index(fields=['trigger', 'created_at'], name='recommendat_trigger_76c37c_idx'),
        ),
        migrations.AddIndex(
            model_name='triggercategorypolicy',
            index=models.Index(fields=['trigger_key', 'enabled', 'rank'], name='trigger_cat_trigger_bcf697_idx'),
        ),
        migrations.AddField(
            model_name='contentstat',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='api.content'),
        ),
        migrations.AddField(
            model_name='usercontentstat',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='api.content'),
        ),
        migrations.AddIndex(
            model_name='contentstat',
            index=models.Index(fields=['updated_at'], name='content_sta_updated_387f81_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentstat',
            index=models.Index(fields=['user_ref', 'updated_at'], name='user_conten_user_re_3c27dd_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentstat',
            index=models.Index(fields=['content'], name='user_conten_content_f1fd02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontentstat',
            unique_together={('user_ref', 'content')},
        ),
    ]
