# Generated by Django 5.2.6 on 2025-09-21 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contentstat_usercontentstat_content_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('user_ref', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('item_kind', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=1)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('trigger', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by', models.CharField(default='mobile', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('url', models.URLField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('place_type', models.CharField(blank=True, default='', max_length=10)),
                ('place_id', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('weather_gate', models.CharField(blank=True, default='', max_length=10)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.content')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.recommendationsession')),
            ],
            options={
                'db_table': 'recommend_delivery',
                'indexes': [models.Index(fields=['user_ref', 'category', '-created_at'], name='recommend_d_user_re_c0d6a5_idx'), models.Index(fields=['session', 'created_at'], name='recommend_d_session_ab5f14_idx'), models.Index(fields=['request_id'], name='recommend_d_request_6c592b_idx')],
            },
        ),
    ]
