# Generated by Django 5.2.6 on 2025-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recommendationdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='channel_quality',
            field=models.FloatField(blank=True, help_text='채널/제공자 품질(0~1)', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='lang',
            field=models.CharField(blank=True, default='', help_text='ko/en 등', max_length=10),
        ),
        migrations.AddField(
            model_name='content',
            name='length_sec',
            field=models.IntegerField(blank=True, help_text='콘텐츠 길이(초)', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='pre_score_base',
            field=models.FloatField(blank=True, help_text='배치 산출 기본 품질 점수(0~1)', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='voice_guided',
            field=models.BooleanField(blank=True, help_text='음성 가이드 여부', null=True),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['lang'], name='content_lang_8b1683_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['length_sec'], name='content_length__fd3272_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['voice_guided'], name='content_voice_g_acb5a4_idx'),
        ),
    ]
