# Generated by Django 5.2.6 on 2025-09-22 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_content_channel_quality_content_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstat',
            name='alpha',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='contentstat',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='usercontentstat',
            name='alpha',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='usercontentstat',
            name='beta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='content',
            name='channel_quality',
            field=models.FloatField(blank=True, help_text='채널/제공자 품질(0~1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='content',
            name='pre_score_base',
            field=models.FloatField(blank=True, help_text='배치 산출 기본 품질 점수(0~1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
