
spring:
  application:
    name: "calendar-diary-server"
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # create, update, validate, none 중 선택
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# 로그 보기 편하게
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

app:
  s3:
    bucket: hellowolrd-s3
    path:
      caricatures: caricature
      snapshots: snapshot
      ultrasounds: ultrasound
  gms:
    base-url: https://gms.ssafy.io/gmsapi
    api-key: ${GMS_KEY}
    model: dall-e-3
    size: 1024x1024

db-scheduler:
  enabled: true
  table-name: scheduled_tasks

healthserver:
  base-url: http://healthserver-svc:8080
  app-token: ${APP_TOKEN}
