spring:
  application:
    name: "gatewayserver"
  data:
    redis:
      host: ${SPRING_REDIS_HOST}   # ← 실제 Redis 서비스 DNS로 교체
      port: ${SPRING_REDIS_PORT}
      database: 0
      password: ${SPRING_REDIS_PASSWORD:}       # 비번 있으면 env/secret로 주입
      timeout: 3s
      lettuce:
        shutdown-timeout: 100ms
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        host-enabled: true
        proto-enabled: true
        port-enabled: true
        prefix-enabled: true
      routes:
        - id: calendar
          uri: lb://CALENDAR-DIARY-SERVER
          predicates:
            - Path=/calendar/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /calendar


        - id: user
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /user

        - id: health
          uri: lb://HEALTH-SERVER
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /health

        - id: weekly
          uri: lb://WEEKLY-SERVER
          predicates:
            - Path=/weekly/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /weekly

        - id: ai
          uri: http://aiserver-svc.apps.svc.cluster.local:8000
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /ai

springdoc:
  swagger-ui:
    path: /swagger-ui                # 공용 UI 경로 (원하면 /docs 로 바꿔도 됨)
    display-request-duration: true
    urls:
      - name: calendar
        url: /calendar/v3/api-docs

      - name: user
        url: /user/v3/api-docs

      - name: health
        url: /health/v3/api-docs

      - name: weekly
        url: /weekly/v3/api-docs

      - name: ai
        url: /ai/schema/




#  cloud:
#    config:
#      uri: http://config-server:8888  # localhost → config-server로 변경
#         uri: ${CONFIG_SERVER_URL}:8888 # 환경변수로 설정


#eureka:
#  client:
#    service-url:
#      defaultZone: http://eurekaserver-svc:8761/eureka


#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    urls:
#      - name: tangram-server
#        #        url: ${CONFIG_SERVER_URL}:8082/v3/api-docs
#        url: /tangram-server/v3/api-docs
#      - name: user-server
