
spring:
  application:
    name: "weekly-server"
  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        auto: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # create, update, validate, none 중 선택
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  s3:
    bucket: hellowolrd-s3
    path:
      foods: food

youtube:
  api:
    key: ${YOUTUBE_API_KEY}